services:
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend

    redis:
        container_name: redis
        image: redis:6.2
        restart: always
        ports:
            - 6379:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - backend

    minio:
        container_name: minio
        image: minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1
        ports:
            - "9000:9000" 
            - "9001:9001" 
        volumes:
            - minio-data:/data 
        environment:
            MINIO_ROOT_USER: ${MINIO_USER} 
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
        command: server /data --console-address ":9001"
        networks:
            - backend

volumes:
    postgres_data:
    redis_data:
    minio-data:

networks:
    backend:
